---
- name: Playbook One
  hosts: all
  collections: keepersecurity.keeper_secrets_manager
  include_vars: secrets.yml

  tasks:
    - name: "Make Test Directory"
      file:
        path: "/home/user/keeper_test/{{ item }}"
        state: directory
        recurse: yes
      loop:
        - ".ssh"

    - name: "Copy Test SSH Keys"
      keeper_copy:
        notation: "OlLZ6JLjnyMOS3CiIPHBjw/field/keyPair[{{ item.notation_key }}]"
        dest: "/home/user/keeper_test/.ssh/{{ item.filename }}"
        mode: "0600"
      loop:
        - { notation_key: "privateKey", filename: "id_rsa" }
        - { notation_key: "publicKey",  filename: "id_rsa.pub" }
